### PR TITLE
Migrate to webpack 4

### PR DESCRIPTION
**Pull request by twang2218**
Grunt => Webpack
=========================

* Extract webpack configuration to separated file.
    * `webpackConfig` => `webpack.config.app.js`: Webpack configuration for App content;
    * `webpack.config.main.js`: Webpack configuration for Electron main process;
        * Copy all files under `desktop/` to `dist/app/` except `package-lock.json;
        * Replace the `@@PUBLIC_KEY_CONTENT` with `app/resources/public-key.pem`'s content;
* Replace `replaceFont()` function with webpack `url-loader`;
* Rearrange `dist`, `tmp` directories to single `dist` directory:
    * `tmp`, `tmp/desktop/app`, `tmp/cordova` => `dist/app`: App content;
    * `dist`, `tmp/desktop` => `dist/build`: Build directory for each platform;
    * `dist/desktop/` => `dist/release`: Release files for each platform;
* `grunt --beta` => `webpack --env.release=beta`;
* Targets:
    * Web: `webpack --env.target=web`
    * Desktop: `webpack --env.target=desktop`
    * Cordova: `webpack --env.target=cordova`
* Release Channels:
    * Stable: `webpack --env.release=stable`
    * Beta: `webpack --env.release=beta`
* Production vs Development:
    * Production: `NODE_ENV=production`
    * Development: `NODE_ENV=development`
* Grunt Tasks:
    * `gitinfo`: `git-revision-webpack-plugin`;
    * `clean`: NPM script with `rimraf` package;
    * `copy`:
        * `copy:html`:
            * `app/index.html` => `app/index.hbs` template;
            * `html-webpack-plugin`;
        * `copy:favicon` => `html-webpack-plugin`;
        * `copy:icons` => `copy-webpack-plugin`;
        * `copy:dist-icons` => `copy-webpack-plugin`;
        * `copy:manifest` => `copy-webpack-plugin`;
        * `copy:dist-manifest` => `copy-webpack-plugin`;
        * `copy:fonts` => webpack's `url-loader`;
        * `copy:desktop-app-content` => `webpack.config.main.js`'s `copy-webpack-plugin`;
    * `eslint` => webpack `eslint-loader`;
    * `sass` => webpack `sass-loader`;
    * `postcss` => webpack plugins:
        * `resolve-url-loader`
        * `css-loader`
        * `optimize-css-assets-webpack-plugin`
        * `style-loader` (fallback)
    * `inline` => webpack plugins:
        * `script-ext-html-webpack-plugin`
        * `html-webpack-inline-source-plugin`
        * `ignore-assets-webpack-plugin`
        * `extract-text-webpack-plugin`
    * `htmlmin` => `html-webpack-plugin`'s `minify`;
    * `string-replace`:
        * `manifest` => `copy-webpack-plugin`
        * `manifest-html` => `app/index.hbs` template
        * `desktop-html` => `app/index.hbs` template
        * `desktop-public-key` => webpack `url-loader`
        * `cordova-html` => `app/index.hbs` template
    * `uglify` => `uglifyjs-webpack-plugin`;
    * `watch` => `webpack-dev-server`
    * `concurrent` => No need for separate watcher because all HTML/JS/CSS are built by `webpack`, so only `webpack-dev-server` is enough;

File modifications
==================

* `app/styles/main.scss`: webpack can resolve the name with `~` prefix, so `../node_modules/` => `~`;
* `desktop/main.js`: Use tempalte quote for "`@@PUBLIC_KEY_CONTENT`" to avoid replace the quote later for multiline string.

Dependencies
=============

* `webpack` upgrade to `^4.12.0`;
* `webpack-dev-server` upgrade to `^3.1.4`;
* `babel-loader` upgrade to `7.1.4` for webpack 4 support;
* `babel-preset-es2015` => `babel-preset-env`;
* `handlebars-loader` upgrade to `1.7.0`;

NPM scripts
==============

* Build app content for Web:
    * `webpack:web`: Production
    * `webpack:web:beta`: Beta
    * `webpack:web:dev`: Development
* Build app content for desktop target:
    * `webpack:desktop`: Production
    * `webpack:desktop:beta`: Beta
    * `webpack:desktop:dev`: Development
    * Internals:
        * `webpack:desktop:app`: App content for desktop
        * `webpack:desktop:main`: Electron main process
        * `webpack:desktop:build`: Build both app content and main process for desktop (without specify whether it's production or development)
* Build app content for cordova
    * `webpack:cordova`
* Webpack dev server
    * `server`: Development
    * `server:prod`: Production
* Electron
    * `electron`: Run electron with `dist/app`;
    * `electron:server`: Run electron with `dist/app` and argument `--htmlpath=http://localhost:8085/`;
* ESLint
    * `eslint`: Run ESLint
* Bundle Analyzer: Use Bundler Analyzer to visualize bundler size stats;
    * `webpack:web:stats`: bundler analysis on Web target;
    * `webpack:desktop:stats`: bundler analysis on Desktop target;
* Clean the build
    * `clean`: Remove `dist` directory
    * `clean:app`: Remove `dist/app` directory
    * `clean:build`: Remove `dist/build` directory
    * `clean:release`: Remove `dist/release` directory

Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by antelle** [comment]
Hi!
Thanks for this! 🎁 
I need some time to test different cases, I'll come up with feedback this weekend.
One important part that I found now:
Desktop app consists of two parts:

1. main.js - it lives in /Applications/KeeWeb.app and is never replaced, this is the app loader
2. app.js - this file is inside asar and can be updated

It looks like everything is joined to one file. If so, please restore it. I can be mistaken, please ignore this comment then.

**Comment by twang2218** [comment]
Yes, you are correct, both `main.js`, `app.js` and their dependencies will be compiled into a single file. And sorry, I didn't realize the update process require them to be separated.

My intention to pass `main.js` and `app.js` to `webpack` are:

1. eliminating the public key loading part in Grunt;
2. eliminating the need for `node_modules` directory.

I will separate the `main.js` and `app.js`.

But, I'm a bit confused about the `node-stream-zip` dependency, could you help me understand the code? I didn't find the reference in those 2 files, do we really need the dependency? I saw the reference in `app/scripts/comp/updater.js` though, what's the relationship between the `updater.js` and `main.js` or `app.js`? Shall we compile the `node-stream-zip` package into `main.js` or `app.js`?

**Comment by antelle** [comment]
This is not needed for the desktop app, where we pack everything in asar, let's revert this change and keep node_modules, that's ok for desktop apps.
Right, `node-stream-zip` is used in updater to extract an update files called `UpdateDesktop.zip`. It contains everything (app.js + node_modules + index.html) excluding `main.js`, which is located in App folder. `main.js` checks signatures of the asar and launches it from AppData folder.
So, please don't run webpack neither on main.js, nor no app.js and other desktop parts.

**Comment by twang2218** [comment]
Rewrote the `webpack.config.main.js`, so there will not be compiling on `desktop/main.js` or `desktop/app.js` anymore, just copy them to `dist/app` as is, except the `@@PUBLIC_KEY_CONTENT` string will be replaced with the content of `app/resources/public-key.pem`, just like what `copy:desktop-public-key` did in the `Gruntfile.js`.

To test it on the electron, just:

```bash
# YARN
yarn clean && yarn webpack:desktop && yarn electron

# NPM
npm run clean && npm run webpack:desktop && npm run electron
```

BTW, I do think the YARN is much more stable and faster than NPM, everytime I run the `npm install` the `package-lock.json` will be modified here or there, even there is nothing changed. It never happend on `yarn`, the `yarn.lock` is always the same if there is nothing changed in the dependencies. I suggest we use `yarn` instead.

**Comment by antelle** [comment]
Thanks for the fast fix, I'll test it this weekend!

**Comment by antelle** [comment]
I tried to run another quick test now. Some observations:
1. App size: `1 298 684` - develop, `1 396 492`
Let's find a reason why. Probably something is not packed correctly.
2. Please remove `fonts` and `stats.json` from `dist`, it should contain only what we need
3. Argon2 is broken (I checked in Safari), please fix it ([example file](https://github.com/keeweb/keeweb/files/2150250/Argon2New.kdbx.zip)):
```
2018-06-29T17:09:08.626Z [argon2] WebAssembly error
TypeError: u.replace is not a function. (In 'u.replace("var Module",h+p)', 'u.replace' is undefined)
(anonymous function) — app:50:285032
``` 
4. Settings > Help > App Information:
`KeeWeb v1.6.3 (&quot;9a7d23b&quot;, 2018-06-29)` - should be `"`, not `&quot;`

Let's fix these first, then I'll test desktop scripts.

**Comment by antelle** [comment]
Argon2 was actually broken in #946

**Comment by twang2218** [comment]
> 1. App size: 1 298 684 - develop, 1 396 492 - webpack
> Let's find the reason. Probably something is not packed correctly or extra modules are included.

The reason is that `argon2.min.js` is missing from bundle in the `develop` branch. It's my bad, I forgot use `raw-loader` for the file. We can verify it by visualize the bundle use `BundlerAnalyzer`.

* `webpack4` branch:



* `develop` branch



After bundle the `argon2.min.js`, the difference between `develop` and `webpack4` branch is very subtle.

> 2. Please remove fonts and stats.json from dist, it should contain only what we need, we don't support browsers that can't load fonts from html

I removed them.

> 3. Argon2 is broken (please ignore this, it's broken in develop as well, I'll fix this)

I fixed it by loading the `argon2.min.js` via `raw-loader`. But I don't know how to test it? Could you show me how?

> 4. Settings > Help > App Information:
> `KeeWeb v1.6.3 (&quot;9a7d23b&quot;, 2018-06-29)` - it should not contain `&quot;` or `"`, just the build number is enough

Done.

**Comment by Coises** [comment]
Most of this is way beyond me... I just want to add a request.

Would you make sure that whatever you do leaves a clean, straightforward way to build desktop and webpage versions, for testing and/or personal use, by those of us who have only Windows or Linux, don’t have a code signing certificate and/or don’t want to build an installer?

See Issue #967 and [my comment](https://github.com/keeweb/keeweb/issues/967#issuecomment-415982521) to it.

**Comment by antelle** [comment]
Building a desktop version is now super complicated yeah (basically it's not supported, but starting electron with dev-server should work). This won't solve it, but web build should become easier.

**Comment by Coises** [comment]
>Building a desktop version is now super complicated

Well, as I described in [that comment](https://github.com/keeweb/keeweb/issues/967#issuecomment-415982521), I’ve been able to do it on Windows 7... and that was without having ever used npm, Electron or Grunt until about a month ago when I started looking at KeeWeb. Mainly, I just had to unravel what Grunt was doing and make a new target that included only the applicable steps.

I’m just hoping any new build system won’t break the possibility of building a desktop version on Windows for testing and personal use. That would be a loss... to me, at least.

**Comment by antelle** [comment]
@Coises absolutely agree. 
This won't become worse with this change, but we should provide a way to build it, like you did in that comment.

**Comment by dploeger** [comment]
@twang2218 I have another request. 😉 In #1056 I changed the aliases of i.e. backbone to use the non-minified versions when building the dev-server. Is this already integrated because of the mode set to "development"? (Sorry, I'm also lacking the knowledge to understand the complete configuration)

**Comment by antelle** [comment]
Hi!

I've upgraded to WebPack 4 manually, merged some changes from this PR. 🎁 

Accepted changes:
- webpack 4
- webpack config separation
- argon2 fixes
- upgraded modules

Rejected changes:
- build system changes: I don't see how moving copy tasks to webpack is better than building manually or with grunt or other task runner. In my opinion, configuration becomes more complicated without visible benefits: let's let module bundlers and task runners do their jobs without interfering with each other.
- yarn: npm can do the same thing nowadays
